config/routes.rb
Rails.application.routes.draw do

  # routes for jbuilder
  namespace :api do
    namespace :yamalogs do
      get '/', action: 'index'
      get '/new', action: 'new'
      get '/:id', action: 'show'
      post '/new', action: 'create'
      patch '/;id', action: 'update'
      delete '/:id', action: 'destroy'
    end
  end

  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
  resources :yamalogs

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/yamalog.rb
class Yamalog < ApplicationRecord
  mount_uploader :yamalog_pic, YamalogPicUploader
  mount_uploader :gpslog, GpslogUploader
  belongs_to :user

  validates :hiking_date, presence: true
  validates :mountain_name, presence: true
  validates :weather, length: { maximum: 20}
  validates :member, length: { maximum: 50}
  validates :route, length: { maximum: 2000}

  def created_by?(user)
    return false unless user
    user_id = user.id
  end
end

app/controllers/api/yamalogs_controller.rb
class Api::YamalogsController < ApplicationController
  before_action :set_yamalog, only: [:show, :update, :destroy]

  #GET /yamalogs
  def index
    @yamalogs = Yamalog.all.order(created_at: :desc)
    render 'index', formats: 'json', handlers: 'jbuilder'
  end

  #GET /yamalogs/:id
  def show
    render 'show', formats: 'json', handlers: 'jbuilder'
  end

  #POST /yamalogs/new
  def create
    @yamalog = Yamalog.new(yamalog_params)
    if @yamalogs.save
      render 'create', formats: 'json', handlers: 'jbuilder'
    else
      render json: @yamalog.errors, status: :unprocessable_entity
    end
  end

  #PATCH /yamalogs/:id
  def update
    if @yamalog.update(yamalog_params)
      render 'update', formats: 'json', handlers: 'jbuilder'
    else
      render json: @yamalog.errors, status: :unprocessable_entity
    end
  end

  #DELETE /yamalogs/:id
  def destroy
    @yamalog.destroy
  end

  private
    def set_yamalog
      @yamalog = Yamalog.find(params[:id])
    end

    def yamalog_params
      params.require(:yamalog).permit(:hiking_date, :mountain_name, :weather, :member, :route, :gpslog, :yamalog_pic)
    end

end

app/controllers/yamalogs_controller.rb
class YamalogsController < ApplicationController
  def index
    @yamalogs = Yamalog.all.order(created_at: :desc)
  end

  def new
    @yamalog = current_user.yamalogs.build
  end

  def create
    @yamalog = current_user.yamalogs.build(yamalog_params)
    if @yamalog.save
      redirect_to @yamalog
    else
      render :new
    end
  end

  def show
    @yamalog = Yamalog.find(params[:id])
  end

  def edit
    @yamalog = current_user.yamalogs.find(params[:id])
  end

  def update
    @yamalog = current_user.yamalogs.find(params[:id])
    if @yamalog.update(yamalog_params)
      redirect_to @yamalog
    else
      render :edit
    end
  end

  def destroy
    @yamalog = current_user.yamalogs.find(params[:id])
    @yamalog.destroy!
    redirect_to yamalogs_path
  end

  private

  def yamalog_params
    params.require(:yamalog).permit(
      :hiking_date, :mountain_name, :weather, :member, :route,
      :yamalog_pic, :yamalog_pic_cache, :remove_yamalog_pic,
      :gpslog, :gpsloc_cache, :remove_gpslog
    )
  end
end

app/helpers/yamalogs_helper.rb
module YamalogsHelper
end

app/views/yamalogs/edit.html.erb
<% now = Time.zone.now %>

<div class="container py-3">
  <h1 class="display-4 mb-5">ヤマログを編集</h1>

  <%= form_for(@yamalog, class: 'form-horizontal', role: 'form') do |f| %>
    <% if @yamalog.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @yamalog.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group row">
      <%= f.label :hiking_date, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.datetime_select :hiking_date, start_year: now.year - 10, end_year: now.year %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :mountain_name, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.text_field :mountain_name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :weather, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.text_field :weather, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :member, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.text_field :member, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :route, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.text_area :route, class: 'form-control', row: 10 %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :yamalog_pic, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <% if @yamalog.yamalog_pic? %>
          <div class="thumbnail">
            <%= image_tag @yamalog.yamalog_pic_url(:thumb) %>
          </div>
        <% end %>
        <%= f.file_field :yamalog_pic %>
        <%= f.hidden_field :yamalog_pic_cache %>
        <% if @yamalog.yamalog_pic? %>
          <div class="checkbox">
            <label>
              <%= f.check_box :remove_yamalog_pic %>
              画像を削除する
            </label>
          </div>
        <% end %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-2">
        <%= f.label :gpslog, class: 'col-form-label' %>
      </div>
      <div class="col-sm-10">
        <% if @yamalog.gpslog? %>
          <div class="thumbnail">
            <%= @yamalog.gpslog %>
          </div>
        <% end %>
        <%= f.file_field :gpslog %>
        <%= f.hidden_field :gpslog_cache %>
        <% if @yamalog.gpslog? %>
          <div class="checkbox">
            <label>
              <%= f.check_box :remove_gpslog %>
              GPSログを削除する
            </label>
          </div>
        <% end %>
      </div>
    </div>

    <%= f.submit '更新', class: 'btn btn-primary', data: { disable_with: '更新中…' } %>

  <% end %>

</div>

app/views/yamalogs/index.html.erb
<div class="container py-3 yamalog-link">
  <h1 class="display-4 mb-5">投稿一覧</h1>

  <div class="row">
    <% @yamalogs.each do |yamalog| %>
      <%= link_to(yamalog) do %>
        <div class="col-sm-4 pb-4">
          <div class="card">
            <%= image_tag("/img/no_image.jpg", class: 'card-img-top') %>
            <div class="card-body">
              <h3 class="card-title card-link"><%= yamalog.mountain_name %></h3>
              <p class="card-text">投稿日：<span><%= yamalog.created_at.strftime('%Y/%m/%d') %></span></p>
              <p class="card-text">投稿者：<span><%= yamalog.user.email %></span></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

</div>

app/views/yamalogs/new.html.erb
<% now = Time.zone.now %>

<div class="container py-3">
  <h1 class="display-4 mb-5">ヤマログを作成</h1>

  <%= form_for(@yamalog, class: 'form-horizontal', role: 'form') do |f| %>
    <% if @yamalog.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @yamalog.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group row">
      <%= f.label :hiking_date, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.datetime_select :hiking_date, start_year: now.year - 10, end_year: now.year %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :mountain_name, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.text_field :mountain_name, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :weather, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.text_field :weather, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :member, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.text_field :member, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :route, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= f.text_area :route, class: 'form-control', row: 10 %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :yamalog_pic, class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <% if @yamalog.yamalog_pic? %>
          <div class="thumbnail">
            <%= image_tag @yamalog.yamalog_pic_url(:thumb) %>
          </div>
        <% end %>
        <%= f.file_field :yamalog_pic %>
        <%= f.hidden_field :yamalog_pic_cache %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-2">
        <%= f.label :gpslog, class: 'col-form-label' %>
      </div>
      <div class="col-sm-10">
        <%= f.file_field :gpslog %>
        <%= f.hidden_field :gpslog_cache %>
      </div>
    </div>

    <%= f.submit '作成', class: 'btn btn-primary', data: { disable_with: '作成中…' } %>

  <% end %>

</div>

app/views/yamalogs/show.html.erb
<div class="container py-3">
  <h1 class="display-4 mb-5"><%= @yamalog.mountain_name %></h1>

  <div id="hikelog_info">
    <table class="bordered">
      <tbody>
        <tr>
          <th>投稿者</th>
          <td><%= @yamalog.user.email %></td>
        </tr>
        <tr>
          <th>日付</th>
          <td><%= @yamalog.hiking_date %></td>
        </tr>
        <tr>
          <th>天気</th>
          <td><%= @yamalog.weather %></td>
        </tr>
        <tr>
          <th>メンバー</th>
          <td><%= @yamalog.member %></td>
        </tr>
        <tr>
          <th>ルート</th>
          <td><%= @yamalog.route %></td>
        </tr>
        <% if @yamalog.yamalog_pic? %>
          <tr>
            <th>写真</th>
            <td><%= link_to image_tag(@yamalog.yamalog_pic_url(:thumb)), @yamalog.yamalog_pic_url %></td>
          </tr>
        <% end %>
        <% if @yamalog.gpslog? %>
          <tr>
            <th>GPSログ</th>
            <td>
              <div id="map" class="map"></div>
              <%= hidden_field :yamalog, :gpslog_url, class: 'yamalog_gpslog_url' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% if @yamalog.created_by?(current_user) %>
    <%= link_to 'ヤマログを編集', edit_yamalog_path(@yamalog), class: 'btn btn-info btn-lg' %>
    <%= link_to 'ヤマログを削除', yamalog_path(@yamalog), class: 'btn btn-danger btn-lg', method: :delete, data: { confirm: '本当に削除しますか？' } %>
  <% end %>
</div>