config/routes.rb
Rails.application.routes.draw do

  # routes for jbuilder
  namespace :api do
    namespace :yamalogs do
      get '/', action: 'index'
      get '/new', action: 'new'
      get '/:id', action: 'show'
      post '/new', action: 'create'
      patch '/;id', action: 'update'
      delete '/:id', action: 'destroy'
    end
  end

  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
  resources :yamalogs

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top py-3">
    <div class="container">
      <%= link_to 'Hikerog', root_path, :class => 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to '投稿する', new_yamalog_path, class: 'nav-link' %></li>
          <li class="nav-item"><a class="nav-link" href="/yamalogs">山行一覧</a></li>
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">その他 <span class="caret"></span></a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to 'マイページ', edit_user_registration_path, class: 'dropdown-item' %>
                <a href="#" class="dropdown-item">お問い合わせ</a>
                <div class="dropdown-divider"></div>
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
              </div>
            </li>
          <% else %>
            <li class="nav-item"><%= link_to 'ログイン', new_user_session_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to '新規登録', new_user_registration_path, class: 'nav-link' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>